FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build-env

# RUN apk-install bash

WORKDIR /app

# Explicitly ask for path to be added
ENV PATH="${PATH}:/root/.dotnet/tools"

RUN dotnet tool install --global dotnet-ef --version 3.1.3

# Copy csproj and restore as distinct layers
COPY *.csproj /app
RUN dotnet restore logic-api.csproj

# Copy everything else and build
COPY . /app
RUN dotnet publish logic-api.csproj -c Release -o out

# Run updates
# RUN dotnet ef database update -c PersistedGrantDbContext
# RUN dotnet ef database update -c ConfigurationDbContext

# Build runtime image
# FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
# WORKDIR /app
# COPY --from=build-env /app/out .

COPY ./entrypoint.sh /app

WORKDIR /app

# ENTRYPOINT ["dotnet", "logic-api.dll"]

EXPOSE 80/tcp
RUN chmod +x ./entrypoint.sh
CMD /bin/sh ./entrypoint.sh